### ISSUE TITLE
Portfolio roadmap

### ISSUE THREAD

**Issue by hys25** [hys25/portfolio-admin#3]
# TODO project plan

- **Project feature**
	BE :
	- [x] CRUD for project endpoint

	Admin :
	- [x] Add project page UI
	- [x] Form should include:
			- Project name
			- Main project checkbox ( main projects displayed different on Projects page )
			- Link to website
			- Project stack (optional)
			- Project description 
			- Your impact
			- Brand color HEX (optional) (the idea is to create feature with different color for each project and use it on the project page)
			- Add main image of project
			- Add background animation (optional)
		
 	FE :
	- [x] Project page UI
	Display main image, background animation, project stack, description and your impact.
	On click on project open website (check if it's allowed)
	- [x] Slider
			
	UI:
	- [x] Design images for projects and animation on hover
	- [x] Naming for projects
- **All projects page** 
	BE :
	- [x] GET all projects 

	Admin :
	- [x] Projects page 

	FE :
	- [x] Projects page 
			On hover display image and stack of project
	
	UI:
	- [x] Design images for projects and animation on hover
	- [x] Naming for projects
- **Pagination**
	BE :
	- [ ] SPIKE

	Admin :
	- [ ] SPIKE
- **Contact page**
	BE:
	- [ ] Create CRUD for messages entity
	 
	Admin:
	- [ ] Create messages page and display all received messages
	
	FE:
	- [ ] Contact page with form 
		
- **About page**
	BE: 
	- [x] Create CRUD for skills entity

	FE:
	- [x] About page with a decription of me
	- [x] Link to /contact
	- [x] Display skills
- **More about the website page**
	FE:
	- [x] Describe goals, stack and features of portfolio
- **Auth feature** 
	*BE / admin*
	- [ ] Remember me
	- [ ] Forgot password
- **Tests**
	- [ ] add Jest tests 
- **Mobile for whole website**
	- [x] Make mobile for website 
- **SEO**
	- [x] add SEO
- **Translation feature**
	- [ ] SPIKE
- **Display image on hover on homepage**
	FE:
	- [x] The idea is to show picture only on hover under cursor radius
- **Skills feature**
       BE + Admin is done
	FE:
	- [ ] The idea is to breake all skills by clicking on button (all letters fly in different directions)

**Comment by ArturHorbenko** [comment]
I'll write here small briefing for the next our priority.
So for the task `Project feature - BE - CRUD for project endpoint` let's  create a separate branch from develop with appropriate name and will handle all CRUD actions. Also please provide the latest export from Postman

So as i see in the design, we'll have a form with text field + 2 images. 

![Screenshot 2022-08-22 at 22 37 55](https://user-images.githubusercontent.com/49113142/186057075-75142930-0139-414b-a9ae-38a24bfc16ab.png)

For this case i think the best approach would be to use FormData as the way to send between client and server instead of json. Basically we'll have a one big FormData on the client and our task now is to handle BE part.

I'd  suggest to do in such order
- [x] Learn what is FormData 
- [x] Check how to work with `FormData` in express.js ( library that looks good to me is https://github.com/expressjs/multer )
> https://www.youtube.com/watch?v=wIOpe8S2Mk8 
- [x] Try to create POST request for projects and test it with Postman
> Note : during saving to DB we'll need to save image url in image fields.
- [x] Implement GET request
---------
- [x] For FE admin : create project form + view of created project 
Once it's done let's merge these changes on FE repo too.
---------
- [x] Implement PUT request ( updating the project )
> Note : For the put we'll need to figure out, how to remove unused files 
- [x] Implement DELETE request 
    Things to keep in mind 
    BE
    - we should delete assets on the server along with deleting project
    Admin
    - we should refetch all projects to keep project's list up to date
    - Good practice to have a confirmation modal, so user won't delete a entity right away without warning. I think we can create reusable component for confirmation modal with configurable text, actions on Yes/No

**Comment by hys25** [comment]
## INITIATIVE - Improve Code Quality and Performance

### Epics: Enhance Type Safety & Increase Test Coverage & Upgrade Caching Process

#### Enhance Type Safety

- [ ] Admin typescript setup
- [ ] Backend typescript setup

#### Increase Test Coverage
- [ ] Backend: Main CRUD entities test coverage
- [ ] Admin : Auth e2e 
- [ ] Admin : main entities e2e

#### Upgrade Caching Process
- [x] Admin: upgrade to RTK-Query latest API approach
- [ ] ...
