### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hys25** [hys25/portfolio-admin#4]
# TODO project plan
- **Auth feature** 
	*BE / admin*
	- [ ] Remember me
	Figure out how smart people doing that :)
	- [ ] Forgot password
	Figure out how smart people doing that :)
- **Project feature**
	BE :
	- [ ] CRUD for project endpoint

	Admin :
	- [ ] Add project page UI
	- [ ] Form should include:
			- Project name
			- Main project checkbox ( main projects displayed different on Projects page )
			- Link to website
			- Project stack (optional)
			- Project description 
			- Your impact
			- Brand color HEX (optional) (the idea is to create feature with different color for each project and use it on the project page)
			- Add main image of project
			- Add background animation (optional)
		
 	FE :
	- [ ] Project page UI
	Display main image, background animation, project stack, description and your impact.
	On click on project open website (check if it's allowed)
	- [ ] Slider
			
	UI:
	- [ ] Design images for projects and animation on hover
	- [ ] Naming for projects
- **All projects page** 
	BE :
	- [ ] GET all projects 

	Admin :
	- [ ] Projects page 

	FE :
	- [ ] Projects page 
			On hover display image and stack of project
	
	UI:
	- [ ] Design images for projects and animation on hover
	- [ ] Naming for projects
- **Pagination**
	BE :
	- [ ] Figure out how smart people doing that :)

	Admin :
	- [ ] Figure out how smart people doing that :)
- **Contact page**
	BE:
	- [ ] Create CRUD for messages entity
	 
	Admin:
	- [ ] Create messages page and display all received messages
	
	FE:
	- [ ] Contact page with form 
		
- **About page**
	BE: 
	- [ ] Create CRUD for skills entity

	FE:
	- [ ] About page with a decription of me
	- [ ] Link to /contact
	- [ ] Display skills
- **More about the website page**
	FE:
	- [ ] Desribe goals, stack and features of portfolio
- **Tests**
	- [ ] ?
- **Mobile for whole website**
	- [ ] Make mobile for website 
- **SEO**
	- [ ] ?
- **Translation feature**
	- [ ] Figure out how smart people doing that :)
- **Display image on hover on homepage**
	FE:
	- [ ] The idea is to show picture only on hover under cursor radius
- **Skills feature**
	FE:
	- [ ] The idea is to breake all skills by clicking on button (all letters fly in different directions)
- **CV feature**
	BE:
	- [ ] Create CRUD for cv
	Admin:
	- [ ] Keep the history and display all CV 
	- [ ] Show preview
	- [ ] Possibility upload new CV
